// The MIT License (MIT)

// Copyright (c) 2017 Ben Abelshausen

// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:

// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

namespace Itinero.API.VectorTiles.Mapbox
{
    /// <summary>
    /// Contains code to build tilejson definition for the mapbox vector tiles.
    /// </summary>
    public static class DefinitionBuilder
    {
        /// <summary>
        /// Builds the tile json attribution for the given instance url.
        /// </summary>
        public static string Build(string instanceUrl, string attribution)
        {
            var template = "{\r\n  \"tiles\": [\r\n    \"{instance_url}/tiles/{z}/{x}/{y}.mvt\"\r\n  ],\r\n  \"name\": \"Itinero API Routing-data Vector Tiles\",\r\n  \"format\": \"pbf\",\r\n  \"id\": \"routingdata\",\r\n  \"basename\": \"routingdata\",\r\n  \"attribution\": \"{attribution}\",\r\n  \"description\": \"A tileset generated by the Itinero routing API containg multimodal routing-related data.\",\r\n  \"maxzoom\": 14,\r\n  \"minzoom\": 7,\r\n  \"center\": [ -12.2168, 28.6135, 4 ],\r\n  \"vector_layers\": [\r\n    {\r\n      \"maxzoom\": 14,\r\n      \"fields\": {\r\n        \"brunnel\": \"String\",\r\n        \"ramp\": \"Number\",\r\n        \"class\": \"String\",\r\n        \"service\": \"String\",\r\n        \"oneway\": \"Number\"\r\n      },\r\n      \"minzoom\": 0,\r\n      \"id\": \"transportation\",\r\n      \"description\": \"\"\r\n    }\r\n  ],\r\n  \"bounds\": [ -180, -85.0511, 180, 85.0511 ],\r\n  \"maskLevel\": \"8\",\r\n  \"version\": \"1.0\",\r\n  \"tilejson\": \"2.0.0\"\r\n}";

            template = template.Replace("{instance_url}", instanceUrl);
            template = template.Replace("{attribution}", attribution);

            return template;
        }
    }
}